name: Generate SVG from Lifepixels

on:
  workflow_dispatch: # Allows manual trigger
    inputs:
      query:
        description: 'Organism Name (scientific name; e.g. "Callus callus domesticus")'
        required: true
        default: 'Mus musculus'
      output_dir:
        description: 'File output directory'
        required: true
        default: './profile/organism.svg'
      grid_size:
        description: 'grid size'
        required: false
        default: '30'

jobs:
  update-svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Profile Repo
        uses: actions/checkout@v4

      - name: Generate Bio-Pixel
        uses: jsphu/lifepixels@main 
        with:
          organism_query: ${{ github.event.inputs.query }}
          output_path: ${{ github.event.inputs.output_dir }}
          grid_size: ${{ github.event.inputs.grid_size }}
  
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./profile/organism.svg
          git commit -m "Update Bio-Pixel: ${{ github.event.inputs.query }}" || echo "No changes"
          git push
