name: Generate SVG from Lifepixels

on:
  workflow_dispatch: # Allows manual trigger
    inputs:
      query:
        description: 'Organism Name (scientific name; e.g. "Callus callus domesticus")'
        required: true
        default: 'Mus musculus'

jobs:
  update-svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Profile Repo
        uses: actions/checkout@v4

      - name: Generate Bio-Pixel
        uses: jsphu/lifepixels@main 
        with:
          organism_query: ${{ github.event.inputs.query }}

      - name: Move SVG
        shell: bash
        run: |
          mv ./organism.svg ./profile/organism.svg

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./profile/organism.svg
          git commit -m "Update Bio-Pixel: ${{ github.event.inputs.query }}" || echo "No changes"
          git push
